### PR TITLE
Fix for Issue #120

### PR DESCRIPTION
**Pull request by PatrickvonDeetzen**
Main changes were made in "Source\gofish.prg" and "Source\SF_RegExp\sf_regexp.prg".

### CODE REVIEW

**Comment by DougHennig** [comment]
@lscheffler Can you check out this pull request to make sure it is OK? Thanks.

**Comment by Jimrnelson** [comment]
@DougHennig @lscheffler 

I am curious about the mechanics of how one checks out a pull request like this one.

Obviously, you do not want to merge it into master, because that makes it the new public version.

How then does one take the changes in the pull request into one's local forked repository for testing?

I'm asking this because I would like to know how to do so if such should arise for Thor, for instance.

**Comment by lscheffler** [comment]
@Jimrnelson I answer in Thor discussion. (link follows)

**Comment by lscheffler** [comment]
@PatrickvonDeetzen  Thanks for debugging it, I never run into this. And it looks like you are not the first one :)

The _SF_RegExp_ directory is on my comp a clone of https://github.com/lscheffler/sf_regexp. And this I could not change to assume to see GoFish, it should run on it's own, and therefore not be changed.

It looks like you run GoFish in  **DevelopmentMode** iow as prg. This is the way to former developers of GoFish used to develop, inherited code.

**Run the App instead.**

Even if you are developing GoFish, I must say that **I** do not develop this way, so you are on your own. Since I work the project, all development is done on app level. So this is why SF_Regexp fails.

If you see a different reason to use the GoFish.prg, let me know. Else I think I simply will block GoFish from running as prg. I do not code to use SET PROCEDURE, this is a source of havoc - this is a tool for common use and it should not change others SET PATH.

**Comment by lscheffler** [comment]
Update:

I looked a bit deeper into the startup (I have never touched since I took over). It does some assumptions with SYS(16) that could make a lot of fun. Just run the App, this should work under all circumstances.

**Pull request closed without merging**
