### PR TITLE
Highlight searched text in opened window

### PR DESCRIPTION
**Pull request by nmpetkov**
1. Highlight searched text in opened window. Uses Foxtools.fll.

2. Allows positioning not only in PRG files, but also in others that are somehow related to VFP: SPR, MPR, QPR, H, INI, TXT, XML, HTM. Here, the criteria can be expanded to any text file found in the search results.

### CODE REVIEW

**Comment by lscheffler** [comment]
Thanks I will look it up next week - I'm on the road.

**Comment by nmpetkov** [comment]
Thanks! Here is only the program code. Making it optional is about the interface and can be done additionally if someone wants.

**Comment by lscheffler** [comment]
There is an ATC**C** at one line. ATC is fine. :)    
Just look up how the HTML is generated, finally it needs to determine the same string. You might even reuse the code to get your information.

**Comment by nmpetkov** [comment]
> There is an ATC**C** at one line. ATC is fine. :)

I agree, maybe there is nowhere to get these double-byte characters :-)

**Comment by nmpetkov** [comment]
In the last commit I implemented the search method similar to the one in `gf_resultsform.showhtmlcodeview`

**Comment by nmpetkov** [comment]
Test result: no problems after a few weeks of operation. Selecting search text works great.

**Comment by lscheffler** [comment]
It's only that some might prefer the old way as default, and it needs an option to be implemented.

**Comment by Jimrnelson** [comment]
@lscheffler 

I have commented on this issue before and suggested that this be made an option.  I have changed my mind on this -- I suggest you go ahead and implement it -- I'm pretty sure, without having seen it, that this would be preferable.

I'm guessing that nobody is going to speak up and prefer to go back to the old way.

**Comment by lscheffler** [comment]
@Jimrnelson ok

**Comment by lscheffler** [comment]
@nmpetkov I feel awkward merging just the code into master, since the app and the code would differ. I prefer to download your code and merge it local into the project. And then reject the merge. Are you ok with this? Otherwise you would need to go the whole way populating the app as documented [here](https://github.com/VFPX/GoFish/blob/master/.github/CONTRIBUTING.md), and I merge this.

**Comment by nmpetkov** [comment]
@lscheffler Please do it the best way and with the least effort. I don't have a problem with that, you can even just put a link to this PR and close it.

**Comment by lscheffler** [comment]
@nmpetkov Implemented and pushed

**Pull request closed without merging**
